{% set version = "0.9.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-raveio
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/raveio_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/raveio/raveio_{{ version }}.tar.gz
  sha256: cd6a9d26f6890f80d4e939b2aa5b42621ab919b4ff36fdd6839587cd2984df8e

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r.matlab >=3.6.2
    - r-r6
    - r-callr >=3.7.0
    - r-data.table
    - r-dipsaus
    - r-edfreader >=1.2.1
    - r-filearray >=0.1.3
    - r-fst >=0.9.2
    - r-globals
    - r-glue
    - r-hdf5r >=1.3.4
    - r-jsonlite >=1.7.0
    - r-promises >=1.2.0
    - r-ravetools
    - r-remotes >=2.1.2
    - r-rpymat
    - r-stringr >=1.4.0
    - r-targets >=0.8.0
    - r-threebrain >=0.2.5
    - r-yaml >=2.2.1
  run:
    - r-base
    - r-r.matlab >=3.6.2
    - r-r6
    - r-callr >=3.7.0
    - r-data.table
    - r-dipsaus
    - r-edfreader >=1.2.1
    - r-filearray >=0.1.3
    - r-fst >=0.9.2
    - r-globals
    - r-glue
    - r-hdf5r >=1.3.4
    - r-jsonlite >=1.7.0
    - r-promises >=1.2.0
    - r-ravetools
    - r-remotes >=2.1.2
    - r-rpymat
    - r-stringr >=1.4.0
    - r-targets >=0.8.0
    - r-threebrain >=0.2.5
    - r-yaml >=2.2.1

test:
  commands:
    - $R -e "library('raveio')"           # [not win]
    - "\"%R%\" -e \"library('raveio')\""  # [win]

about:
  home: https://beauchamplab.github.io/raveio/
  license: GPL-3.0-only
  summary: |
    Includes multiple cross-platform read/write interfaces for 'RAVE' project. 'RAVE'
    stands for "R analysis and visualization of human intracranial electroencephalography
    data". The whole project aims at providing powerful free-source package that analyze
    brain recordings from patients with electrodes placed on the cortical surface or
    inserted into the brain. 'raveio' as part of this project provides tools to read/write
    neurophysiology data from/to 'RAVE' file structure, as well as several popular formats
    including  'EDF(+)', 'Matlab', 'BIDS-iEEG', and 'HDF5', etc. Documentation and examples
    about 'RAVE' project are provided at <https://openwetware.org/wiki/RAVE>, and the
    paper by John F. Magnotti, Zhengjia Wang, Michael S. Beauchamp (2020) <doi:10.1016/j.neuroimage.2020.117341>;
    see 'citation("raveio")' for details.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - dipterix
    - beauchamplab

# Package: raveio
# Type: Package
# Title: File-System Toolbox for RAVE Project
# Version: 0.0.9
# Language: en-US
# Authors@R: c( person("Zhengjia", "Wang", email = "dipterix.wang@gmail.com", role = c("aut", "cre", "cph")), person("Beauchamp lab", email = "beauchamplab@gmail.com", role = c("cph", "fnd")) )
# Description: Includes multiple cross-platform read/write interfaces for 'RAVE' project. 'RAVE' stands for "R analysis and visualization of human intracranial electroencephalography data". The whole project aims at providing powerful free-source package that analyze brain recordings from patients with electrodes placed on the cortical surface or inserted into the brain. 'raveio' as part of this project provides tools to read/write neurophysiology data from/to 'RAVE' file structure, as well as several popular formats including  'EDF(+)', 'Matlab', 'BIDS-iEEG', and 'HDF5', etc. Documentation and examples about 'RAVE' project are provided at <https://openwetware.org/wiki/RAVE>, and the paper by John F. Magnotti, Zhengjia Wang, Michael S. Beauchamp (2020) <doi:10.1016/j.neuroimage.2020.117341>; see 'citation("raveio")' for details.
# BugReports: https://github.com/beauchamplab/raveio/issues
# URL: https://beauchamplab.github.io/raveio/
# License: GPL-3
# Encoding: UTF-8
# RoxygenNote: 7.2.1
# SystemRequirements: little-endian platform
# Imports: utils, data.table, edfReader (>= 1.2.1), dipsaus, filearray (>= 0.1.3), fst (>= 0.9.2), glue, globals, hdf5r (>= 1.3.4), jsonlite (>= 1.7.0), R.matlab (>= 3.6.2), R6, stringr (>= 1.4.0), yaml (>= 2.2.1), targets (>= 0.8.0), callr (>= 3.7.0), remotes (>= 2.1.2), promises (>= 1.2.0), threeBrain (>= 0.2.5)
# Suggests: rpymat, visNetwork, testthat, reticulate, knitr, rmarkdown, bs4Dash, clustermq, shiny, shinybusy, shinyWidgets, arrow, ravetools, later (>= 1.3.0)
# NeedsCompilation: no
# Packaged: 2022-10-13 20:42:41 UTC; dipterix
# Author: Zhengjia Wang [aut, cre, cph], Beauchamp lab [cph, fnd]
# Maintainer: Zhengjia Wang <dipterix.wang@gmail.com>
# Repository: CRAN
# Date/Publication: 2022-10-14 09:00:05 UTC
